version: "3.9"
services:
  app:
    build: ./docker/php
    volumes:
      - ./src:/data
  web:
    image: nginx:1.20-alpine
    ports:
      - 8080:80
    volumes:
      - ./src:/data
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /data
  db:
    build: ./docker/mysql
    volumes:
      - db-store:/var/lib/mysql
  node:
    build: ./docker/node
    volumes:
      - ./src:/data
    tty: true
    ports:
      - "3000:3000"
    command: yarn dev

volumes:
  db-store: